name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - name: Setup Rust
#       run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
#     - name: Setup wasm-pack
#       run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build
      run: wasm-pack build --target web
    - name: Compress
      run: brotli pkg/*.wasm
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pkg
        path: ./pkg
